spring:
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      username: sa
      password:
      generate-unique-name: false
      ddl-auto: update
      initialization-mode: always
   batch:
      initialize-schema: always
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      defer-datasource-initialization: true  
   h2:
      console:
         enabled: true
         path: /h2