INSERT INTO HOME_APPLIANCE (ID, NAME, CATEGORY, PRICE) VALUES (HOME_APPLIANCE_SEQ.nextval, 'TV', 'Electronic', 1000);
INSERT INTO HOME_APPLIANCE (ID, NAME, CATEGORY, PRICE) VALUES (HOME_APPLIANCE_SEQ.nextval, 'REFRIGERATOR', 'Electronic', 1200);
INSERT INTO HOME_APPLIANCE (ID, NAME, CATEGORY, PRICE) VALUES (HOME_APPLIANCE_SEQ.nextval, 'WALKING PAD', 'Mechanic', 300);
INSERT INTO HOME_APPLIANCE (ID, NAME, CATEGORY, PRICE) VALUES (HOME_APPLIANCE_SEQ.nextval, 'ROCKER', 'Mechanic', 290);
INSERT INTO HOME_APPLIANCE (ID, NAME, CATEGORY, PRICE) VALUES (HOME_APPLIANCE_SEQ.nextval, 'AIR CONDITIONER', 'Electronic', 550);